# Generated by Django 5.0.6 on 2024-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.PositiveBigIntegerField()),
            ],
        ),
    ]
